$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
resources:
  - name: Disable Loopback Check
    type: Microsoft.Windows/Registry
    properties:
      keyPath: HKLM\System\CurrentControlSet\Control\Lsa
      valueName: DisableLoopbackCheck
      valueData:
        String: 1
