# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  resources:
    - resource: MyResources/MyScoop
      directives:
        description: Scoop
    - resource: MyResources/MyScoopPackage
      directives:
        description: dotnet-sdk
      settings:
        packageName: dotnet-sdk
    # - resource: PSDesiredStateConfiguration/WindowsOptionalFeature
    #   directives:
    #     description: IIS-WebServer
    #   settings:
    #     name: IIS-WebServer
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: PowerShell
      settings:
        id: Microsoft.PowerShell
        source: winget
  configurationVersion: 0.2.0
