# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
  - settings:
      MinVersion: 10.0.22000
    resource: Microsoft.Windows.Developer/OsVersion
    directives:
      description: Verify min OS version requirement
      allowPrerelease: true
  configurationVersion: 0.2.0
  resources:
  - resource: MyResources/MyScoop
    directives:
      description: Scoop
  - settings:
      packageName: dotnet-sdk
    resource: MyResources/MyScoopPackage
    directives:
      description: Scoop Package - dotnet-sdk
  - settings:
      packageName: gh
    resource: MyResources/MyScoopPackage
    directives:
      description: Scoop Package - gh
  - settings:
      id: Microsoft.PowerShell
      source: winget
    resource: Microsoft.WinGet.DSC/WinGetPackage
    directives:
      description: WinGet Package - winget/Microsoft.PowerShell
  - settings:
      id: Microsoft.PowerToys
      source: winget
    resource: Microsoft.WinGet.DSC/WinGetPackage
    directives:
      description: WinGet Package - winget/Microsoft.PowerToys

