properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  resources:
    - resource: MyResources/MyScoop
      directives:
        description: Scoop
    - resource: MyResources/MyScoopPackage
      directives:
        description: Scoop Package - [packageName]
      settings:
        - packageName: dotnet-sdk
        - packageName: gh
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: WinGet Package - [source]/[id]
      settings:
        - id: Microsoft.PowerShell
          source: winget
        - id: Microsoft.PowerToys
          source: winget
  configurationVersion: 0.2.0
