name: Pester Tests CI

on: [push, pull_request]

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
            Install-Module -Name Functional -Force -Scope CurrentUser -AllowClobber -SkipPublisherCheck

      - name: Import custom modules
        shell: pwsh
        run: |
            $customModulesPath = Join-Path $env:GITHUB_WORKSPACE "DSC\Modules"
            $env:PSModulePath = "$customModulesPath;$env:PSModulePath"

      - name: Run Pester Tests
        shell: pwsh
        run: |
            Invoke-Pester -CI